version: "3"

tasks:
    migrate-up:
        cmds:
            - dbmate -u "${OWNER_DATABASE_URL:-$DATABASE_URL}" --migrations-dir "./repository/migrations" --migrations-table "public.dbmate_migrations_users" --no-dump-schema --wait migrate

    migrate-down:
        cmds:
            - dbmate -u "${OWNER_DATABASE_URL:-$DATABASE_URL}" --migrations-dir "./repository/migrations" --migrations-table "public.dbmate_migrations_users" --no-dump-schema --wait rollback
