version: "3"

includes:
  example:
    taskfile: ./example/taskfile.yml
    dir: ./example

tasks:
  lint:
    desc: Run golangci-lint against the whole module
    cmds:
      - golangci-lint run ./...
    silent: true

  lint:fix:
    desc: Run golangci-lint against the whole module and auto-fix issues
    cmds:
      - golangci-lint run --fix ./...
    silent: true
