package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"strings"
	"text/template"
)

var (
	clientName = flag.String("client", "", "client struct")
)

type Field struct {
	Name string
	Type string
}
type Method struct {
	Name     string
	Request  Field
	Response Field
	Address  string
	IsEvent  bool
}

type BindingGenData struct {
	Package                  string
	ServiceName              string
	ClientImplementationName string
	ClientName               string
	Source                   string
	Methods                  []Method
	MethodsForRegisterServer []Method
}

func newBindingGenData(serviceName string) BindingGenData {
	clientName := strings.ReplaceAll(serviceName, "Service", "Client")

	return BindingGenData{
		ServiceName:              serviceName,
		ClientName:               clientName,
		ClientImplementationName: clientName + "Implementation",
		Package:                  os.Getenv("GOPACKAGE"),
		Source:                   os.Getenv("GOFILE"),
		Methods:                  []Method{},
		MethodsForRegisterServer: []Method{},
	}
}

func main() {
	flag.Parse()

	goFile := os.Getenv("GOFILE")
	_, _ = fmt.Fprintf(os.Stdout, "Running generating  client for '%s' from %s\n", *clientName, goFile)

	fset := token.NewFileSet() // positions are relative to fset

	// get ast Node of whole file;
	ff, err := parser.ParseFile(fset, goFile, nil, parser.ParseComments)
	if err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)

		return
	}

	ast.Inspect(ff, func(n ast.Node) bool {
		d, ok := n.(*ast.GenDecl)
		if !ok || d.Tok != token.TYPE {
			return true
		}

		spec, ok := d.Specs[0].(*ast.TypeSpec)
		if !ok || spec.Name.Name != *clientName {
			return true
		}

		client := newBindingGenData(*clientName)
		if structDecl, ok := spec.Type.(*ast.InterfaceType); ok {
			parseMethods(&client, structDecl, fset)
		}

		return true
	})
}

func parseMethods(client *BindingGenData, interDecl *ast.InterfaceType, fset *token.FileSet) {
	for _, field := range interDecl.Methods.List {
		parseField(client, field, fset)
	}

	writeBindGen(client)
}

func parseField(client *BindingGenData, field *ast.Field, fset *token.FileSet) {
	if identType, ok := field.Type.(*ast.Ident); ok {
		decl, ok := identType.Obj.Decl.(*ast.TypeSpec)
		if !ok {
			panic(*clientName + " should have only functional methods  or embedded interfaces")
		}

		inte, ok := decl.Type.(*ast.InterfaceType)
		if !ok {
			panic(*clientName + " should have only functional methods  or embedded interfaces")
		}

		parseMethods(client, inte, fset)

		return
	}

	funcType, ok := field.Type.(*ast.FuncType)
	if !ok {
		panic(*clientName + " should have only functional methods  or embedded interfaces")
	}

	requestArguments := fieldsFromList(fset, funcType.Params)
	results := fieldsFromList(fset, funcType.Results)

	methods := buildMethods(field, requestArguments, results)
	if len(methods) > 0 {
		client.Methods = append(client.Methods, methods[0])
	}

	client.MethodsForRegisterServer = append(client.MethodsForRegisterServer, methods...)
}

func fieldsFromList(fset *token.FileSet, list *ast.FieldList) []Field {
	fields := make([]Field, 0, len(list.List))
	for _, param := range list.List {
		fields = append(fields, Field{
			Name: getName(param),
			Type: getTypeName(fset, param.Type),
		})
	}

	return fields
}

func buildMethods(field *ast.Field, requestArguments []Field, results []Field) []Method {
	methods := make([]Method, 0, len(field.Doc.List))
	for _, comment := range field.Doc.List {
		address, isEvent := findBindAddress(comment)

		methods = append(methods, Method{
			Name:     field.Names[0].Name,
			Request:  requestArguments[1],
			Response: results[0],
			Address:  address,
			IsEvent:  isEvent,
		})
	}

	return methods
}

func writeBindGen(client *BindingGenData) {
	cwd, err := os.Getwd()
	if err != nil {
		panic(err)
	}

	tmpl := template.Must(template.New("client").Parse(templateCode))

	path := cwd + "/bind-gen.go"

	f, err := os.Create(path) //nolint:gosec // path is derived from os.Getwd(), not user input
	if err != nil {
		panic(err)
	}

	defer func() {
		_ = f.Close()
	}()

	err = tmpl.Execute(f, client)
	if err != nil {
		panic(err)
	}
}

func findBindAddress(comment *ast.Comment) (string, bool) {
	const methodPrefix = "// bind-method: "
	const eventPrefix = "// bind-event: "

	parts := strings.Split(comment.Text, "?")
	basePart := parts[0]

	var address string

	var isEvent bool

	if after, ok := strings.CutPrefix(basePart, methodPrefix); ok {
		address = after
	} else if after, ok := strings.CutPrefix(basePart, eventPrefix); ok {
		address = after
		isEvent = true
	}

	return address, isEvent
}

func getName(p *ast.Field) string {
	if len(p.Names) == 0 {
		return ""
	}

	return p.Names[0].Name
}

func getTypeName(fset *token.FileSet, exp ast.Expr) string {
	var tmp bytes.Buffer

	_ = printer.Fprint(&tmp, fset, exp)

	return tmp.String()
}

//nolint:lll
var templateCode = `
//nolint:unparam
// Code generated by genbind tool. DO NOT EDIT.
// source: {{.Source}}

package {{.Package}}

import (
	"context"

	"github.com/geruz/rizotto/bb"
)

func RegisterServer(srv {{.ClientName}}) {
	{{range .MethodsForRegisterServer}}{{if .IsEvent}}bb.MustRegisterEvent("{{.Address}}", srv.{{.Name}}){{else}}bb.MustRegister("{{.Address}}", srv.{{.Name}}){{end}}
	{{end}}
}

type (
	{{range .Methods}}{{.Name}} func(ctx context.Context, req {{.Request.Type}}) ({{.Response.Type}}, bb.ServiceError)
	{{end}}
)


type {{.ClientImplementationName}} struct {
{{range .Methods}}    _{{.Name}} {{.Name}}
{{end}}
}

{{range .Methods}}func (c {{$.ClientImplementationName}}) {{.Name}}(ctx context.Context, req {{.Request.Type}}) ({{.Response.Type}}, bb.ServiceError) {
	return c._{{.Name}}(ctx, req)
}
{{end}}

func BindClient() {{.ClientName}} {
	return {{.ClientImplementationName}}{
		{{range .MethodsForRegisterServer}}{{if not .IsEvent}}_{{.Name}}: bb.MustBind[{{.Name}}]("{{.Address}}"),
		{{else}}//_{{.Name}}: bb.MustRegisterEvent[{{.Name}}]("{{.Address}}),
		{{end}}{{end}}
	}
}
`
