
//nolint:unparam
// Code generated by genbind tool. DO NOT EDIT.
// source: client.go

package user

import (
	"context"
	
	"github.com/geruz/rizotto/bb"
)

func RegisterServer(srv UserClient) {
	bb.MustRegister("http://user-service/user/get", srv.GetUserRPC)
	bb.MustRegister("http://user-service/user/select", srv.SelectUsersRPC)
	
}

type (
	GetUserRPC func(ctx context.Context, req GetUserRequest) (User, bb.ServiceError)
	SelectUsersRPC func(ctx context.Context, req SelectUserRequest) (UserList, bb.ServiceError)
	
)


type UserClientImplementation struct {
    _GetUserRPC GetUserRPC
    _SelectUsersRPC SelectUsersRPC

}

func (c UserClientImplementation) GetUserRPC(ctx context.Context, req GetUserRequest) (User, bb.ServiceError) {
	return c._GetUserRPC(ctx, req)
}
func (c UserClientImplementation) SelectUsersRPC(ctx context.Context, req SelectUserRequest) (UserList, bb.ServiceError) {
	return c._SelectUsersRPC(ctx, req)
}


func BindClient() UserClient {
	return UserClientImplementation{
		_GetUserRPC: bb.MustBind[GetUserRPC]("http://user-service/user/get"),
		_SelectUsersRPC: bb.MustBind[SelectUsersRPC]("http://user-service/user/select"),
		
	}
}
